function openMember(id){let x=state.members.find(x=>x.id===id)||{};modal(id?'แก้ไขสมาชิก':'เพิ่มสมาชิก',`<form onsubmit="saveMember(event,'${id||''}')"><div class="formgrid"><div class="field full"><label>ชื่อในเกม</label><input name="name" required value="${esc(x.name||'')}"></div><div class="field"><label>ตำแหน่ง</label><select name="role">${['หัวหน้า HR','รองหัวหน้า HR','สมาชิกหลัก HR','ประธาน','รองประธาน','สมาชิกสภา'].map(v=>`<option ${x.role===v?'selected':''}>${v}</option>`)}</select></div><div class="field"><label>รูปโปรไฟล์</label><input name="image" type="file" accept="image/*"></div></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกข้อมูล</button></div></form>`)}
async function saveMember(e,id){e.preventDefault();let f=e.target,x=state.members.find(x=>x.id===id),image=await imgFile(f.image),v={id:id||uid(),name:f.name.value,role:f.role.value,image:image||x?.image||fallback};x?Object.assign(x,v):state.members.push(v);done('บันทึกข้อมูลสมาชิกแล้ว')}
function openOrg(k,id){let x=state[k].find(x=>x.id===id)||{};modal(id?'แก้ไของค์กร':'เพิ่ม'+labels[k],`<form onsubmit="saveOrg(event,'${k}','${id||''}')"><div class="simple-org-head"><img src="${x.logo||orgFallback}"><div><div class="eyebrow">BYOU CITY · ${k==='gangs'?'GANG':k==='families'?'FAMILY':'MC'} REGISTRY</div><h3>${id?'แก้ไขข้อมูล':'ลงทะเบียน'}${labels[k]}</h3><p>กรอกข้อมูลองค์กร ส่วนตำแหน่งจัดการในรายชื่อสมาชิก</p></div></div><div class="formgrid"><div class="field full"><label>ชื่อ${labels[k]}</label><input name="name" required placeholder="กรอกชื่อ${labels[k]}" value="${esc(x.name||'')}"></div>${k==='gangs'?`<div class="field"><label>Tier</label><select name="tier"><option ${x.tier==='Gold'?'selected':''}>Gold</option><option ${x.tier==='Silver'?'selected':''}>Silver</option></select></div><div class="field"><label>สถานะแม่สี</label><select name="motherColor"><option value="false" ${!x.motherColor?'selected':''}>แก๊งทั่วไป</option><option value="true" ${x.motherColor?'selected':''}>◆ แก๊งแม่สี</option></select></div>`:''}<div class="field"><label>ชื่อสีประจำ${labels[k]}</label><input name="colorName" placeholder="เช่น ดำ แดง น้ำเงิน ทอง" value="${esc(x.colorName||'')}"></div><div class="field"><label>เลือกสีประจำ${labels[k]}</label><input type="color" name="color" value="${x.color||'#e5c45a'}"></div><div class="field full"><label>โลโก้</label><input type="file" name="logo" accept="image/*"></div></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกข้อมูล</button></div></form>`)}
async function saveOrg(e,k,id){e.preventDefault();let f=e.target,x=state[k].find(x=>x.id===id),logo=await imgFile(f.logo),v={id:id||uid(),name:f.name.value,leader:x?.leader||'',deputy:x?.deputy||'',tier:f.tier?.value,color:f.color.value,colorName:f.colorName?.value||x?.colorName||'',motherColor:f.motherColor?.value==='true',logo:logo||x?.logo||orgFallback,members:x?.members||[]};x?Object.assign(x,v):state[k].push(v);done('บันทึกข้อมูลองค์กรแล้ว')}
function orgDetail(k,id,tab='members'){let o=state[k].find(x=>x.id===id),max=orgLimit(k,o),wf=state.welfare.filter(x=>x.orgId===id||x.orgName===o.name);modal(esc(o.name),`<div class="detailhero"><img src="${o.logo||orgFallback}"><div><h2>${esc(o.name)}</h2><p>${labels[k]} · ${o.members.length}/${max} คน</p></div><button class="btn" style="margin-left:auto" onclick="openOrg('${k}','${id}')">แก้ไข</button></div><div class="tabs"><button class="${tab==='members'?'active':''}" onclick="orgDetail('${k}','${id}','members')">สมาชิก (${o.members.length})</button><button class="${tab==='welfare'?'active':''}" onclick="orgDetail('${k}','${id}','welfare')">สวัสดิการ (${wf.length})</button></div>${tab==='members'?`<div>${o.members.map(m=>`<div class="minirow"><img src="${m.image||fallback}"><div class="grow"><b>${esc(m.name)}</b><small>${esc(m.role)}</small></div><button class="iconbtn" onclick="orgMember('${k}','${id}','${m.id}')">แก้</button><button class="iconbtn" onclick="delOrgMember('${k}','${id}','${m.id}')">ลบ</button></div>`).join('')||'<div class="empty">ยังไม่มีสมาชิก</div>'}</div><button class="btn gold" style="width:100%;margin-top:14px" onclick="orgMember('${k}','${id}')" ${o.members.length>=max?'disabled':''}>＋ เพิ่มสมาชิก</button>`:`<div>${wf.map(w=>`<div class="minirow"><div class="welfare-person-icon">♟</div><div class="grow"><b>${w.benefit}</b><small>ผู้รับ: ${esc(w.recipient||'ยังไม่ระบุ')} · ${w.date||'-'}</small></div><span class="status ${w.received?'yes':'no'}">${w.received?'✓ ได้รับแล้ว':'✕ ยังไม่ได้รับ'}</span></div>`).join('')||'<div class="empty">ยังไม่มีประวัติ</div>'}</div>`}<div class="formfoot"><button class="btn danger" onclick="delOrg('${k}','${id}')">ลบองค์กร</button><button class="btn" onclick="closeModal()">ปิด</button></div>`)}
function orgMember(k,oid,mid){let o=state[k].find(x=>x.id===oid),m=o.members.find(x=>x.id===mid)||{};modal(mid?'แก้ไขสมาชิก':'เพิ่มสมาชิก',`<form onsubmit="saveOrgMember(event,'${k}','${oid}','${mid||''}')"><div class="formgrid"><div class="field full"><label>ชื่อในเกม</label><input name="name" required value="${esc(m.name||'')}"></div><div class="field"><label>ตำแหน่ง</label><input name="role" required value="${esc(m.role||'สมาชิก')}"></div><div class="field"><label>รูปโปรไฟล์</label><input name="image" type="file" accept="image/*"></div></div><div class="formfoot"><button type="button" class="btn" onclick="orgDetail('${k}','${oid}')">ยกเลิก</button><button class="btn gold">บันทึก</button></div></form>`)}
async function saveOrgMember(e,k,oid,mid){e.preventDefault();let o=state[k].find(x=>x.id===oid),m=o.members.find(x=>x.id===mid),f=e.target,image=await imgFile(f.image),v={id:mid||uid(),name:f.name.value,role:f.role.value,image:image||m?.image||fallback};if(m)Object.assign(m,v);else if(o.members.length<orgLimit(k,o))o.members.push(v);save();render();showPage(k,true);orgDetail(k,oid);toast('บันทึกสมาชิกแล้ว')}
function delOrgMember(k,oid,mid){if(!confirm('ยืนยันการลบสมาชิก?'))return;let o=state[k].find(x=>x.id===oid);o.members=o.members.filter(x=>x.id!==mid);save();render();showPage(k,true);orgDetail(k,oid);toast('ลบสมาชิกแล้ว')}
function openOutfit(id){let x=state.outfits.find(x=>x.id===id)||{},type=x.orgType||'แก๊ง',k=typeKey(type),parts=k==='gangs'?[['suit','สูท'],['hood','ฮู้ด'],['armor','เกราะ'],['tshirt','เสื้อยืด'],['mod1','MOD 1'],['mod2','MOD 2']]:[['set','ฮู้ด'],['armor','เกราะ'],['tshirt','เสื้อยืด'],['mod1','MOD 1'],['mod2','MOD 2']];if(k==='gangs'&&x.set&&!x.hood)x.hood=true;modal(id?'แก้ไขชุดองค์กร':'เพิ่มชุดองค์กร',`<form onsubmit="saveOutfit(event,'${id||''}')"><div class="formgrid"><div class="field"><label>ประเภทองค์กร</label><select name="orgType" onchange="refreshOutfitOrg(this.value)">${['แก๊ง','ครอบครัว','MC'].map(v=>`<option ${type===v?'selected':''}>${v}</option>`)}</select></div><div class="field"><label>ชื่อองค์กร (เลือกจากระบบ)</label><select id="outfitOrg" name="orgId" required><option value="">เลือกองค์กร</option>${state[k].map(o=>`<option value="${o.id}" ${x.orgId===o.id||x.orgName===o.name?'selected':''}>${esc(o.name)}${o.motherColor?' · แม่สี':''}</option>`)}</select></div><div class="field full outfit-checks"><label>รายการชุดที่มี</label><div>${parts.map(([key,label])=>`<label class="outfit-check"><input name="${key}" type="checkbox" ${x[key]?'checked':''}><span>${label}</span></label>`).join('')}</div></div><div class="field full"><label>รูปชุด</label><input name="image" type="file" accept="image/*"></div></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกชุดองค์กร</button></div></form>`)}
function refreshOutfitOrg(type){let k=typeKey(type);$('#outfitOrg').innerHTML='<option value="">เลือกองค์กร</option>'+state[k].map(o=>`<option value="${o.id}">${esc(o.name)}${o.motherColor?' · แม่สี':''}</option>`).join('')}
async function saveOutfit(e,id){e.preventDefault();let f=e.target,k=typeKey(f.orgType.value),x=state.outfits.find(x=>x.id===id),o=state[k].find(o=>o.id===f.orgId.value);if(!o)return toast('กรุณาเลือกองค์กรจากระบบ','bad');let image=await imgFile(f.image),isGang=k==='gangs',v={id:id||uid(),outfitId:x?.outfitId||'',outfitName:x?.outfitName||'',orgType:f.orgType.value,orgId:o.id,orgName:o.name,suit:isGang?f.suit.checked:false,hood:isGang?f.hood.checked:false,set:isGang?f.hood.checked:f.set.checked,armor:f.armor.checked,tshirt:f.tshirt.checked,mod1:f.mod1.checked,mod2:f.mod2.checked,clothes:false,clothesMod:false,image:image||x?.image||orgFallback};x?Object.assign(x,v):state.outfits.push(v);done('บันทึกชุดองค์กรแล้ว')}
function outfitOrgDetail(k,id){let o=state[k].find(x=>x.id===id);if(!o)return;let rows=state.outfits.filter(x=>x.orgId===id||x.orgName===o.name),partLabels=k==='gangs'?[['suit','สูท'],['hood','ฮู้ด'],['armor','เกราะ'],['tshirt','เสื้อยืด'],['mod1','MOD 1'],['mod2','MOD 2']]:[['set','ฮู้ด'],['armor','เกราะ'],['tshirt','เสื้อยืด'],['mod1','MOD 1'],['mod2','MOD 2']],max=partLabels.length;modal('คลังชุดองค์กร',`<div class="detailhero outfit-detailhero ${o.motherColor?'mother-vault':''}"><img src="${o.logo||orgFallback}"><div><div class="eyebrow">${labels[k]} · OUTFIT VAULT${o.motherColor?' · MOTHER COLOR':''}</div><h2>${esc(o.name)}</h2><p>${o.motherColor?'แม่สี '+esc(o.colorName||'')+' · ':''}${rows.length} รายการในคลัง</p></div><button class="btn gold" style="margin-left:auto" onclick="openOutfit()">＋ เพิ่มรายการ</button></div><div class="outfit-detail-grid">${rows.map(x=>{if(k==='gangs'&&x.set&&!x.hood)x.hood=true;let count=partLabels.filter(([key])=>x[key]).length;return `<article class="outfit-detail-card ${o.motherColor?'mother-outfit':''}"><div class="outfit-detail-image"><img src="${x.image||orgFallback}"><span>${count}/${max} รายการ</span></div><div class="outfit-detail-info"><div><small>OUTFIT CHECKLIST</small><h3>รายการชุดที่มี</h3></div><div class="outfit-detail-actions"><button class="iconbtn" onclick="openOutfit('${x.id}')">แก้ไข</button><button class="iconbtn" onclick="del('outfits','${x.id}')">ลบ</button></div></div><div class="outfit-part-table check-mode">${partLabels.map(([key,label])=>`<div class="${x[key]?'has':'none'}"><span>${label}</span><b>${x[key]?'✓ มี':'—'}</b></div>`).join('')}</div></article>`}).join('')||'<div class="empty">องค์กรนี้ยังไม่มีชุดในคลัง</div>'}</div><div class="formfoot"><button class="btn" onclick="closeModal()">ปิด</button></div>`)}
const typeKey=t=>t==='แก๊ง'?'gangs':t==='ครอบครัว'?'families':'mc';
function openAuction(id){let x=(state.auctionCars||[]).find(x=>x.id===id)||{};modal(id?'แก้ไขข้อมูลรถประมูล':'เพิ่มรถประมูล',`<form onsubmit="saveAuction(event,'${id||''}')"><div class="auction-form-head"><div class="security-shield">◆</div><div><div class="eyebrow">BYOU CITY · AUCTION GARAGE</div><h2>ทะเบียนรถประมูล</h2><p>บันทึกผู้ถือครองและแก๊งต้นสังกัดของรถ</p></div></div><div class="formgrid"><div class="field"><label>ชื่อรถ</label><input name="carName" required placeholder="เช่น Lamborghini Huracán" value="${esc(x.carName||'')}"></div><div class="field"><label>โมเดล / Spawn Name</label><input name="model" placeholder="เช่น huracan" value="${esc(x.model||'')}"></div><div class="field"><label>ทะเบียนรถ</label><input name="plate" required placeholder="เช่น BYOU 888" value="${esc(x.plate||'')}"></div><div class="field"><label>ชื่อผู้ถือครอง</label><input name="holder" required placeholder="ชื่อในเกม" value="${esc(x.holder||'')}"></div><div class="field full"><label>แก๊งต้นสังกัด (เลือกจากระบบ)</label><select name="gangId"><option value="">ไม่สังกัดแก๊ง</option>${state.gangs.map(g=>`<option value="${g.id}" ${x.gangId===g.id?'selected':''}>${esc(g.name)} · Tier ${esc(g.tier||'Gold')}</option>`)}</select></div><div class="field"><label>ราคาประมูล</label><input name="price" type="number" min="0" step="1" placeholder="0" value="${esc(x.price||'')}"></div><div class="field"><label>วันที่รับรถ</label><input name="date" type="date" value="${x.date||new Date().toISOString().slice(0,10)}"></div><div class="field"><label>สถานะ</label><select name="status">${['ถือครอง','โอนแล้ว','ยึดคืน','รอส่งมอบ'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`)}</select></div><div class="field"><label>รูปรถ</label><input name="image" type="file" accept="image/*"></div><div class="field full"><label>หมายเหตุ</label><textarea name="note" rows="3" placeholder="รายละเอียดเพิ่มเติม">${esc(x.note||'')}</textarea></div></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกรถประมูล</button></div></form>`)}
async function saveAuction(e,id){e.preventDefault();state.auctionCars=Array.isArray(state.auctionCars)?state.auctionCars:[];let f=e.target,x=state.auctionCars.find(x=>x.id===id),gang=state.gangs.find(g=>g.id===f.gangId.value),image=await imgFile(f.image),v={id:id||uid(),carName:f.carName.value,model:f.model.value,plate:f.plate.value.toUpperCase(),holder:f.holder.value,gangId:gang?.id||'',gangName:gang?.name||'ไม่สังกัดแก๊ง',gangColor:gang?.color||'#e5c45a',price:Number(f.price.value||0),date:f.date.value,status:f.status.value,note:f.note.value,image:image||x?.image||orgFallback};x?Object.assign(x,v):state.auctionCars.push(v);done('บันทึกข้อมูลรถประมูลแล้ว')}
function openWelfare(id){let x=state.welfare.find(x=>x.id===id)||{},type=x.type||'แก๊ง',k=typeKey(type);modal(id?'แก้ไขสวัสดิการ':'เพิ่มสวัสดิการ',`<form onsubmit="saveWelfare(event,'${id||''}')"><div class="formgrid"><div class="field"><label>ประเภทองค์กร</label><select name="type" onchange="refreshOrgSelect(this.value)">${['แก๊ง','ครอบครัว','MC'].map(v=>`<option ${type===v?'selected':''}>${v}</option>`)}</select></div><div class="field"><label>ชื่อองค์กร (เลือกจากระบบ)</label><select id="wfOrg" name="orgId" required>${state[k].map(o=>`<option value="${o.id}" ${x.orgId===o.id||x.orgName===o.name?'selected':''}>${esc(o.name)}</option>`)}</select></div><div class="field full welfare-recipient-field"><label>ชื่อผู้รับสวัสดิการ</label><input name="recipient" required placeholder="กรอกชื่อคนที่รับ เช่น BYOU SOMCHAI" value="${esc(x.recipient||'')}"><small>ชื่อบุคคลที่มารับของแทนองค์กร</small></div><div class="field"><label>ประเภทสวัสดิการ</label><select name="benefit">${['Gold','Silver','Fam','MC','ไม้','มีด'].map(v=>`<option ${x.benefit===v?'selected':''}>${v}</option>`)}</select></div><div class="field"><label>วันที่</label><input type="date" name="date" value="${x.date||new Date().toISOString().slice(0,10)}"></div><div class="field full"><label>สถานะ</label><select name="received"><option value="true" ${x.received?'selected':''}>✅ ได้รับแล้ว</option><option value="false" ${x.received===false?'selected':''}>❌ ยังไม่ได้รับ</option></select></div></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึก</button></div></form>`)}
function refreshOrgSelect(type){$('#wfOrg').innerHTML=state[typeKey(type)].map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('')}function saveWelfare(e,id){e.preventDefault();let f=e.target,k=typeKey(f.type.value),o=state[k].find(x=>x.id===f.orgId.value);if(!o)return toast('กรุณาเพิ่มองค์กรก่อน','bad');let x=state.welfare.find(x=>x.id===id),v={id:id||uid(),type:f.type.value,orgId:o.id,orgName:o.name,recipient:f.recipient.value.trim(),benefit:f.benefit.value,date:f.date.value,received:f.received.value==='true'};x?Object.assign(x,v):state.welfare.push(v);done('บันทึกสวัสดิการแล้ว')}
function welfareOrgDetail(k,id){let o=state[k].find(x=>x.id===id);if(!o)return;let rows=state.welfare.filter(w=>w.orgId===id||w.orgName===o.name);modal('ประวัติสวัสดิการ',`<div class="detailhero welfare-detailhero"><img src="${o.logo||orgFallback}"><div><div class="eyebrow">${labels[k]} · BENEFIT HISTORY</div><h2>${esc(o.name)}</h2><p>${rows.length} รายการสวัสดิการ</p></div><button class="btn gold" style="margin-left:auto" onclick="openWelfare()">＋ เพิ่ม</button></div><div class="welfare-history">${rows.map(w=>`<div class="welfare-history-row"><div class="welfare-person-icon">♟</div><div class="grow"><b>${esc(w.recipient||'ยังไม่ระบุชื่อผู้รับ')}</b><small>${esc(w.benefit)} · ${w.date||'-'}</small></div><span class="status ${w.received?'yes':'no'}">${w.received?'✓ รับแล้ว':'✕ ยังไม่ได้รับ'}</span><button class="iconbtn" onclick="openWelfare('${w.id}')">แก้</button><button class="iconbtn" onclick="del('welfare','${w.id}')">ลบ</button></div>`).join('')||'<div class="empty">องค์กรนี้ยังไม่มีประวัติสวัสดิการ</div>'}</div><div class="formfoot"><button class="btn" onclick="closeModal()">ปิด</button></div>`)}
function del(k,id){if(!confirm('ยืนยันการลบข้อมูลนี้?'))return;state[k]=state[k].filter(x=>x.id!==id);done('ลบข้อมูลแล้ว')}function delOrg(k,id){if(!confirm('ยืนยันการลบองค์กรและสมาชิกทั้งหมด?'))return;state[k]=state[k].filter(x=>x.id!==id);done('ลบองค์กรแล้ว')}
function editPlace(i){let old=i===undefined?'':state.places[i];modal(i===undefined?'เพิ่มสถานที่':'แก้ไขสถานที่',`<form onsubmit="savePlace(event,${i===undefined?'null':i})"><div class="field"><label>ชื่อสถานที่</label><input name="place" required value="${esc(old)}"></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึก</button></div></form>`)}function savePlace(e,i){e.preventDefault();i===null?state.places.push(e.target.place.value):state.places[i]=e.target.place.value;done('บันทึกสถานที่แล้ว');showPage('wheel')}function deletePlace(i){if(state.places.length<=2)return toast('วงล้อต้องมีอย่างน้อย 2 สถานที่','bad');state.places.splice(i,1);save();render();showPage('wheel');toast('ลบสถานที่แล้ว')}
function editActivity(i){let old=i===undefined?'':state.activityItems[i];modal(i===undefined?'เพิ่มตัวเลือกกิจกรรม':'แก้ไขตัวเลือกกิจกรรม',`<form onsubmit="saveActivity(event,${i===undefined?'null':i})"><div class="activity-modal-icon">✹</div><div class="field"><label>ชื่อกิจกรรม / ของรางวัล / ผู้เข้าร่วม</label><input name="activity" required maxlength="60" placeholder="เช่น เงินรางวัล $50,000" value="${esc(old)}"></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกตัวเลือก</button></div></form>`)}
function switchWheelMode(mode){$('#storyWheelPane')?.classList.toggle('active',mode==='story');$('#customWheelPane')?.classList.toggle('active',mode==='custom');$('#customWheel2Pane')?.classList.toggle('active',mode==='custom2');$$('.wheel-switcher button').forEach(b=>b.classList.toggle('active',b.dataset.wheelMode===mode));if(mode==='story')drawWheel();else if(mode==='custom')drawActivityWheel();else drawCustomWheel2()}
function editWheelTitle(mode){let title=state.wheelTitles?.[mode]||'วงล้อ';modal('ตั้งชื่อวงล้อ',`<form onsubmit="saveWheelTitle(event,'${mode}')"><div class="wheel-title-modal"><i>${mode==='story'?'01':mode==='custom'?'02':'03'}</i><div><span>CUSTOM WHEEL NAME</span><h2>เปลี่ยนชื่อวงล้อ</h2></div></div><div class="field"><label>ชื่อวงล้อ</label><input name="title" required maxlength="36" placeholder="เช่น สุ่มรายชื่อผู้เล่น" value="${esc(title)}"></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกชื่อ</button></div></form>`)}
function saveWheelTitle(e,mode){e.preventDefault();state.wheelTitles=state.wheelTitles||{};state.wheelTitles[mode]=e.target.title.value.trim();done('เปลี่ยนชื่อวงล้อแล้ว')}
function saveActivity(e,i){e.preventDefault();state.activityItems=Array.isArray(state.activityItems)?state.activityItems:[];i===null?state.activityItems.push(e.target.activity.value):state.activityItems[i]=e.target.activity.value;done('บันทึกตัวเลือกแล้ว');showPage('wheel',true);switchWheelMode('custom')}
function deleteActivity(i){if(state.activityItems.length<=2)return toast('วงล้อต้องมีอย่างน้อย 2 ตัวเลือก','bad');if(!confirm('ยืนยันการลบตัวเลือกนี้?'))return;state.activityItems.splice(i,1);save();render();showPage('wheel',true);switchWheelMode('custom');toast('ลบตัวเลือกแล้ว')}
function drawActivityWheel(){let c=$('#activityWheelCanvas');if(!c)return;let items=state.activityItems||[],ctx=c.getContext('2d'),n=items.length,r=384,cx=400,cy=400,palette=['#c7a23b','#2c183d','#8d6720','#151927','#5d2d68','#17140d'];ctx.clearRect(0,0,800,800);for(let i=0;i<n;i++){let a=i*Math.PI*2/n-Math.PI/2,b=(i+1)*Math.PI*2/n-Math.PI/2,mid=(a+b)/2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,b);ctx.closePath();ctx.fillStyle=palette[i%palette.length];ctx.fill();ctx.strokeStyle='rgba(255,229,145,.62)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(cx,cy);ctx.rotate(mid);ctx.translate(r*.65,0);if(Math.cos(mid)<0)ctx.rotate(Math.PI);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fff0b0';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=5;ctx.font=`600 ${n>10?14:18}px Kanit`;let t=items[i]||'';ctx.fillText(t.length>18?t.slice(0,17)+'…':t,0,0);ctx.restore()}ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='#f0d36f';ctx.lineWidth=14;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,72,0,Math.PI*2);ctx.fillStyle='#100c17';ctx.fill();ctx.strokeStyle='rgba(219,164,255,.55)';ctx.lineWidth=4;ctx.stroke()}
let activityRotation=0,activitySpinning=false;function spinActivityWheel(){let items=state.activityItems||[];if(activitySpinning||items.length<2)return;activitySpinning=true;let idx=Math.floor(Math.random()*items.length),slice=360/items.length,target=360-(idx*slice+slice/2),rounds=5+Math.floor(Math.random()*3);activityRotation+=rounds*360+((target-activityRotation%360+360)%360);$('#activityWheelCanvas').style.transform=`rotate(${activityRotation}deg)`;$('#activitySpin').disabled=true;let clicks=setInterval(tick,130);setTimeout(()=>{clearInterval(clicks);activitySpinning=false;$('#activitySpin').disabled=false;activityWinner(items[idx])},4400)}
function activityWinner(name){modal('✹ ผลการสุ่ม',`<div class="activity-winner"><div class="winner-rays"></div><span>BYOU CITY RANDOM RESULT</span><h1>${esc(name)}</h1><p>ผลลัพธ์จากวงล้อกิจกรรม / รายชื่อ</p></div><div class="formfoot"><button class="btn" onclick="closeModal()">ปิด</button><button class="btn gold" onclick="closeModal();spinActivityWheel()">✹ สุ่มใหม่</button></div>`)}
function editCustomWheel2Item(i){let items=state.customWheel2Items||[],old=i===undefined?'':items[i];modal(i===undefined?'เพิ่มตัวเลือกวงล้อที่ 3':'แก้ไขตัวเลือกวงล้อที่ 3',`<form onsubmit="saveCustomWheel2Item(event,${i===undefined?'null':i})"><div class="activity-modal-icon custom2-icon">03</div><div class="field"><label>ชื่อ / กิจกรรม / รางวัล</label><input name="item" required maxlength="60" placeholder="กรอกตัวเลือก" value="${esc(old)}"></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกตัวเลือก</button></div></form>`)}
function saveCustomWheel2Item(e,i){e.preventDefault();state.customWheel2Items=Array.isArray(state.customWheel2Items)?state.customWheel2Items:[];i===null?state.customWheel2Items.push(e.target.item.value):state.customWheel2Items[i]=e.target.item.value;done('บันทึกวงล้อที่ 3 แล้ว');showPage('wheel',true);switchWheelMode('custom2')}
function deleteCustomWheel2Item(i){if((state.customWheel2Items||[]).length<=2)return toast('วงล้อต้องมีอย่างน้อย 2 ตัวเลือก','bad');if(!confirm('ยืนยันการลบตัวเลือกนี้?'))return;state.customWheel2Items.splice(i,1);save();render();showPage('wheel',true);switchWheelMode('custom2');toast('ลบตัวเลือกแล้ว')}
function drawCustomWheel2(){let c=$('#customWheel2Canvas');if(!c)return;let items=state.customWheel2Items||[],ctx=c.getContext('2d'),n=items.length,r=384,cx=400,cy=400,palette=['#b58a2d','#113b46','#684518','#15262e','#8d6720','#0c2027'];ctx.clearRect(0,0,800,800);for(let i=0;i<n;i++){let a=i*Math.PI*2/n-Math.PI/2,b=(i+1)*Math.PI*2/n-Math.PI/2,mid=(a+b)/2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,b);ctx.closePath();ctx.fillStyle=palette[i%palette.length];ctx.fill();ctx.strokeStyle='rgba(255,229,145,.62)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(cx,cy);ctx.rotate(mid);ctx.translate(r*.65,0);if(Math.cos(mid)<0)ctx.rotate(Math.PI);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fff0b0';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=5;ctx.font=`600 ${n>10?14:18}px Kanit`;let t=items[i]||'';ctx.fillText(t.length>18?t.slice(0,17)+'…':t,0,0);ctx.restore()}ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='#e7cc6c';ctx.lineWidth=14;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,72,0,Math.PI*2);ctx.fillStyle='#07161a';ctx.fill();ctx.strokeStyle='rgba(82,207,206,.55)';ctx.lineWidth=4;ctx.stroke()}
let custom2Rotation=0,custom2Spinning=false;function spinCustomWheel2(){let items=state.customWheel2Items||[];if(custom2Spinning||items.length<2)return;custom2Spinning=true;let idx=Math.floor(Math.random()*items.length),slice=360/items.length,target=360-(idx*slice+slice/2),rounds=5+Math.floor(Math.random()*3);custom2Rotation+=rounds*360+((target-custom2Rotation%360+360)%360);$('#customWheel2Canvas').style.transform=`rotate(${custom2Rotation}deg)`;$('#custom2Spin').disabled=true;let clicks=setInterval(tick,130);setTimeout(()=>{clearInterval(clicks);custom2Spinning=false;$('#custom2Spin').disabled=false;customWheel2Winner(items[idx])},4400)}
function customWheel2Winner(name){modal('✦ ผลการสุ่ม',`<div class="activity-winner custom2-winner"><div class="winner-rays"></div><span>BYOU CITY · ${esc(state.wheelTitles?.custom2||'WHEEL 03')}</span><h1>${esc(name)}</h1><p>ผลลัพธ์จากวงล้อที่ 3</p></div><div class="formfoot"><button class="btn" onclick="closeModal()">ปิด</button><button class="btn gold" onclick="closeModal();spinCustomWheel2()">✦ สุ่มใหม่</button></div>`)}
function drawWheel(){let c=$('#wheelCanvas');if(!c)return;let ctx=c.getContext('2d'),n=state.places.length,r=384,cx=400,cy=400;ctx.clearRect(0,0,800,800);for(let i=0;i<n;i++){let a=i*Math.PI*2/n-Math.PI/2,b=(i+1)*Math.PI*2/n-Math.PI/2,mid=(a+b)/2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,b);ctx.closePath();ctx.fillStyle=i%2?'#17140d':'#c7a23b';ctx.fill();ctx.strokeStyle='rgba(255,232,145,.55)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(cx,cy);ctx.rotate(mid);ctx.translate(r*.66,0);if(Math.cos(mid)<0)ctx.rotate(Math.PI);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=i%2?'#f5dc7e':'#171207';ctx.font=`600 ${n>10?15:18}px Kanit`;let t=state.places[i];ctx.fillText(t.length>15?t.slice(0,14)+'…':t,0,0);ctx.restore()}ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='#f3db79';ctx.lineWidth=14;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,72,0,Math.PI*2);ctx.fillStyle='#0b0a08';ctx.fill();ctx.strokeStyle='rgba(229,196,90,.45)';ctx.lineWidth=3;ctx.stroke()}
let rotation=0,spinning=false;function tick(){try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=950;g.gain.value=.025;o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.025)}catch(e){}}function spinWheel(){if(spinning||!state.places.length)return;spinning=true;let idx=Math.floor(Math.random()*state.places.length),slice=360/state.places.length,target=360-(idx*slice+slice/2),rounds=5+Math.floor(Math.random()*3);rotation+=rounds*360+((target-rotation%360+360)%360);$('#wheelCanvas').style.transform=`rotate(${rotation}deg)`;$('#spin').disabled=true;let clicks=setInterval(tick,130);setTimeout(()=>{clearInterval(clicks);spinning=false;$('#spin').disabled=false;winner(state.places[idx])},4400)}function winner(name){modal('📍 สถานที่ที่สุ่มได้',`<div style="text-align:center;padding:25px 10px"><div class="eyebrow">STORY LOCATION</div><h1 style="font-size:30px;color:var(--gold2);margin:12px">${esc(name)}</h1><p style="color:var(--muted)">ขอให้เป็นสตอรี่ที่ดีใน BYOU CITY</p></div><div class="formfoot"><button class="btn" onclick="closeModal()">ปิด</button><button class="btn gold" onclick="closeModal();spinWheel()">🎲 สุ่มใหม่</button></div>`)}
function openSearchResult(page,id,kind='org'){
 let openExact=()=>{let box=$('#searchpop'),input=$('#globalSearch');if(box)box.classList.remove('show');if(input)input.value='';showPage(page,true);setTimeout(()=>{if(kind==='member')openMember(id);else if(kind==='org')orgDetail(page,id);else if(kind==='outfit')openOutfit(id);else if(kind==='welfare')openWelfare(id);else if(kind==='auction')openAuction(id);else if(kind==='place'){switchWheelMode('story');editPlace(Number(id))}else if(kind==='activity'){switchWheelMode('custom');editActivity(Number(id))}else if(kind==='custom2'){switchWheelMode('custom2');editCustomWheel2Item(Number(id))}},80)};
 if(typeof editUnlocked!=='undefined'&&!editUnlocked&&typeof openSecurity==='function')return openSecurity(openExact);
 openExact();
}
function pageSearchRows(page){
 let members=()=>state.members.map(x=>({id:x.id,name:x.name,search:x.name+' '+(x.role||''),type:'สมาชิก',page:'members',kind:'member',pic:x.image,meta:x.role||''}));
 let orgs=k=>(state[k]||[]).map(x=>({id:x.id,name:x.name,search:x.name+' '+(x.tier||'')+' '+(x.colorName||''),type:labels[k],page:k,kind:'org',pic:x.logo,meta:k==='gangs'?`Tier ${x.tier||'Gold'}`:(x.colorName||'กดเพื่อเปิดข้อมูล')}));
 if(page==='members')return members();
 if(['gangs','families','mc'].includes(page))return orgs(page);
 if(page==='outfits')return (state.outfits||[]).map(x=>({id:x.id,name:x.orgName||'ชุดองค์กร',search:(x.orgName||'')+' '+(x.orgType||'')+' '+(x.gangTier||''),type:'ชุด'+(x.orgType||'องค์กร'),page:'outfits',kind:'outfit',pic:x.image,meta:(x.orgType||'องค์กร')+(x.gangTier?' · Tier '+x.gangTier:'')}));
 if(page==='welfare')return (state.welfare||[]).map(x=>({id:x.id,name:x.orgName||'สวัสดิการ',search:(x.orgName||'')+' '+(x.recipient||'')+' '+(x.benefit||'')+' '+(x.type||''),type:'สวัสดิการ',page:'welfare',kind:'welfare',pic:orgFallback,meta:(x.recipient||'ยังไม่ระบุผู้รับ')+' · '+(x.benefit||'')}));
 if(page==='auction')return (state.auctionCars||[]).map(x=>({id:x.id,name:x.carName||'รถประมูล',search:(x.carName||'')+' '+(x.model||'')+' '+(x.plate||'')+' '+(x.holder||'')+' '+(x.gangName||''),type:'รถประมูล',page:'auction',kind:'auction',pic:x.image,meta:(x.plate||'NO PLATE')+' · '+(x.holder||'ยังไม่ระบุผู้ถือ')}));
 if(page==='wheel')return [...(state.places||[]).map((name,id)=>({id,name,search:name,type:'สถานที่',page:'wheel',kind:'place',pic:orgFallback,meta:'วงล้อสถานที่'})),...(state.activityItems||[]).map((name,id)=>({id,name,search:name,type:'กิจกรรม',page:'wheel',kind:'activity',pic:orgFallback,meta:'วงล้อกิจกรรม'})),...(state.customWheel2Items||[]).map((name,id)=>({id,name,search:name,type:'วงล้อ 03',page:'wheel',kind:'custom2',pic:orgFallback,meta:'วงล้อรายชื่อเพิ่มเติม'}))];
 return [...members(),...orgs('gangs'),...orgs('families'),...orgs('mc')];
}
function currentSearchPage(){let nav=document.querySelector('#nav button.active[data-page]')?.dataset.page,page=document.querySelector('#pages > .page.active')?.id;return nav||page||'home'}
function search(q){q=q.trim().toLowerCase();let box=$('#searchpop');if(!q){box.classList.remove('show');return}let page=currentSearchPage(),scope={home:'ทุกข้อมูล',members:'สมาชิกหน่วยงาน',gangs:'แก๊ง',families:'ครอบครัว',mc:'MC',outfits:'ชุดองค์กร',welfare:'สวัสดิการ',auction:'รถประมูล',wheel:'ระบบวงล้อ'}[page]||'หน้านี้',rows=pageSearchRows(page).filter(x=>(x.search||x.name||'').toLowerCase().includes(q)),head=`<div style="padding:9px 14px;color:#e5c45a;font-size:11px;letter-spacing:.08em;border-bottom:1px solid rgba(229,196,90,.15)">ค้นหาเฉพาะหน้า · ${scope}</div>`;box.innerHTML=head+(rows.length?rows.map(x=>`<div class="result" onclick="openSearchResult('${x.page}','${x.id}','${x.kind}')"><img src="${x.pic||fallback}"><div><b>${esc(x.name)}</b><small>${esc(x.meta||'กดเพื่อเปิดแก้ไข')}</small></div><em>${x.type} ›</em></div>`).join(''):'<div class="empty" style="padding:25px">ไม่พบข้อมูลในหน้านี้</div>');box.classList.add('show')}
async function init(){$('#nav').onclick=e=>{let b=e.target.closest('button');if(b)showPage(b.dataset.page)};$('#menubtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#globalSearch').oninput=e=>search(e.target.value);$('#modalback').onclick=e=>{if(e.target===e.currentTarget)closeModal()};setInterval(()=>{let d=new Date();$('#clock').textContent=d.toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});$('#date').textContent=d.toLocaleDateString('th-TH',{weekday:'long',day:'numeric',month:'long'})},1000);await connectSupabase();try{await loadScript('byou-roster.js');installOfficialRoster();installHrRoster()}catch(e){console.warn('Roster import unavailable',e)}render();save();setTimeout(()=>$('#splash').classList.add('hide'),900)}

/* แยกแก๊งตาม Tier ในฟอร์มชุดองค์กรและสวัสดิการ */
function tierOrgOptions(type,tier,selectedId='',selectedName=''){
 let k=typeKey(type),orgs=state[k]||[];
 if(k==='gangs')orgs=orgs.filter(o=>(o.tier||'Gold')===(tier||'Gold'));
 return '<option value="">เลือกองค์กร</option>'+orgs.map(o=>`<option value="${o.id}" ${selectedId===o.id||selectedName===o.name?'selected':''}>${esc(o.name)}${k==='gangs'?' · Tier '+esc(o.tier||'Gold'):''}${o.motherColor?' · แม่สี':''}</option>`).join('');
}
function outfitPartOptions(type,data={}){
 let parts=type==='แก๊ง'?[['suit','สูท'],['hood','ฮู้ด'],['armor','เกราะ'],['tshirt','เสื้อยืด'],['mod1','MOD 1'],['mod2','MOD 2']]:[['set','ฮู้ด'],['armor','เกราะ'],['tshirt','เสื้อยืด'],['mod1','MOD 1'],['mod2','MOD 2']];
 return parts.map(([key,label])=>`<label class="outfit-check"><input name="${key}" type="checkbox" ${data[key]?'checked':''}><span>${label}</span></label>`).join('');
}
function openOutfit(id){
 let x=state.outfits.find(x=>x.id===id)||{},type=x.orgType||'แก๊ง',k=typeKey(type),selected=state[k]?.find(o=>o.id===x.orgId||o.name===x.orgName),tier=selected?.tier||x.gangTier||'Gold';
 if(k==='gangs'&&x.set&&!x.hood)x.hood=true;
 modal(id?'แก้ไขชุดองค์กร':'เพิ่มชุดองค์กร',`<form onsubmit="saveOutfit(event,'${id||''}')"><div class="formgrid"><div class="field"><label>ประเภทองค์กร</label><select name="orgType" onchange="refreshOutfitOrg(this.value)">${['แก๊ง','ครอบครัว','MC'].map(v=>`<option ${type===v?'selected':''}>${v}</option>`)}</select></div><div class="field" id="outfitTierField" ${k==='gangs'?'':'style="display:none"'}><label>Tier แก๊ง</label><select id="outfitTier" name="gangTier" onchange="refreshOutfitTier(this.value)"><option ${tier==='Gold'?'selected':''}>Gold</option><option ${tier==='Silver'?'selected':''}>Silver</option></select></div><div class="field full"><label>ชื่อองค์กร (เลือกจากระบบ)</label><select id="outfitOrg" name="orgId" required>${tierOrgOptions(type,tier,x.orgId,x.orgName)}</select></div><div class="field full outfit-checks"><label>รายการชุดที่มี</label><div id="outfitChecksList">${outfitPartOptions(type,x)}</div></div><div class="field full"><label>รูปชุด</label><input name="image" type="file" accept="image/*"></div></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึกชุดองค์กร</button></div></form>`);
}
function refreshOutfitOrg(type){
 let isGang=type==='แก๊ง',tierField=$('#outfitTierField'),tier=$('#outfitTier')?.value||'Gold';
 if(tierField)tierField.style.display=isGang?'':'none';
 let org=$('#outfitOrg');if(org)org.innerHTML=tierOrgOptions(type,tier);
 let checks=$('#outfitChecksList');if(checks)checks.innerHTML=outfitPartOptions(type);
}
function refreshOutfitTier(tier){let org=$('#outfitOrg');if(org)org.innerHTML=tierOrgOptions('แก๊ง',tier)}
async function saveOutfit(e,id){
 e.preventDefault();let f=e.target,k=typeKey(f.orgType.value),x=state.outfits.find(x=>x.id===id),o=state[k].find(o=>o.id===f.orgId.value);
 if(!o)return toast('กรุณาเลือกองค์กรจากระบบ','bad');
 let has=name=>!!f.elements.namedItem(name)?.checked,image=await imgFile(f.image),isGang=k==='gangs',hood=isGang?has('hood'):has('set'),v={id:id||uid(),outfitId:x?.outfitId||'',outfitName:x?.outfitName||'',orgType:f.orgType.value,orgId:o.id,orgName:o.name,gangTier:isGang?(o.tier||f.gangTier?.value||'Gold'):'',suit:isGang&&has('suit'),hood:isGang&&hood,set:hood,armor:has('armor'),tshirt:has('tshirt'),mod1:has('mod1'),mod2:has('mod2'),clothes:false,clothesMod:false,image:image||x?.image||orgFallback};
 x?Object.assign(x,v):state.outfits.push(v);done('บันทึกชุดองค์กรแล้ว');
}

function openWelfare(id){
 let x=state.welfare.find(x=>x.id===id)||{},type=x.type||'แก๊ง',k=typeKey(type),selected=state[k]?.find(o=>o.id===x.orgId||o.name===x.orgName),tier=selected?.tier||x.gangTier||'Gold';
 modal(id?'แก้ไขสวัสดิการ':'เพิ่มสวัสดิการ',`<form onsubmit="saveWelfare(event,'${id||''}')"><div class="formgrid"><div class="field"><label>ประเภทองค์กร</label><select name="type" onchange="refreshOrgSelect(this.value)">${['แก๊ง','ครอบครัว','MC'].map(v=>`<option ${type===v?'selected':''}>${v}</option>`)}</select></div><div class="field" id="welfareTierField" ${k==='gangs'?'':'style="display:none"'}><label>Tier แก๊ง</label><select id="welfareTier" name="gangTier" onchange="refreshWelfareTier(this.value)"><option ${tier==='Gold'?'selected':''}>Gold</option><option ${tier==='Silver'?'selected':''}>Silver</option></select></div><div class="field full"><label>ชื่อองค์กร (เลือกจาก Tier ที่เลือก)</label><select id="wfOrg" name="orgId" required>${tierOrgOptions(type,tier,x.orgId,x.orgName)}</select></div><div class="field full welfare-recipient-field"><label>ชื่อผู้รับสวัสดิการ</label><input name="recipient" required placeholder="กรอกชื่อคนที่รับ เช่น BYOU SOMCHAI" value="${esc(x.recipient||'')}"><small>ชื่อบุคคลที่มารับของแทนองค์กร</small></div><div class="field"><label>ประเภทสวัสดิการ</label><select name="benefit">${['Gold','Silver','Fam','MC','ไม้','มีด'].map(v=>`<option ${x.benefit===v?'selected':''}>${v}</option>`)}</select></div><div class="field"><label>วันที่</label><input type="date" name="date" value="${x.date||new Date().toISOString().slice(0,10)}"></div><div class="field full"><label>สถานะ</label><select name="received"><option value="true" ${x.received?'selected':''}>✅ ได้รับแล้ว</option><option value="false" ${x.received===false?'selected':''}>❌ ยังไม่ได้รับ</option></select></div></div><div class="formfoot"><button type="button" class="btn" onclick="closeModal()">ยกเลิก</button><button class="btn gold">บันทึก</button></div></form>`);
}
function refreshOrgSelect(type){
 let isGang=type==='แก๊ง',tierField=$('#welfareTierField'),tier=$('#welfareTier')?.value||'Gold';
 if(tierField)tierField.style.display=isGang?'':'none';
 let org=$('#wfOrg');if(org)org.innerHTML=tierOrgOptions(type,tier);
}
function refreshWelfareTier(tier){let org=$('#wfOrg');if(org)org.innerHTML=tierOrgOptions('แก๊ง',tier)}
